# Generated by Django 2.2.3 on 2019-08-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20190817_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='shortname',
        ),
    ]
